#!/usr/bin/env php
<?php

// --------------------------------------------------------------
// Aktifkan output buffering
// --------------------------------------------------------------
ob_start();

// --------------------------------------------------------------
// Catat timer awal (untuk benchmark)
// --------------------------------------------------------------
define('RAKIT_START', microtime(true));

// --------------------------------------------------------------
// Definisikan beberapa konstanta yang berguna.
// --------------------------------------------------------------
define('DS', DIRECTORY_SEPARATOR);
define('CRLF', "\r\n");
define('TAB', "\t");
define('CR', "\r");
define('LF', "\n");

// --------------------------------------------------------------
// Include konstanta path milik framework.
// --------------------------------------------------------------
require __DIR__ . DS . 'paths.php';

// --------------------------------------------------------------
// Panggil init script sebelum first boot.
// --------------------------------------------------------------
require path('system') . 'init.php';

// --------------------------------------------------------------
// Bootstrap file core milik framework.
// --------------------------------------------------------------
require path('system') . 'core.php';

// --------------------------------------------------------------
// Pastikan script dijalankan via console.
// --------------------------------------------------------------
is_cli() or exit('Please run this script from your console.');

// --------------------------------------------------------------
// Panggil consolenya.
// --------------------------------------------------------------
require path('system') . 'console' . DS . 'boot.php';
